Creat a docker machine to let the tester run on docker
mintlayer/qa-test pull request #1
Opened 2023-02-15 11:41 UTC by fabiofabbrucci

2023-02-15 12:22 UTC, renie requested changes
First of all, thanks for the initiative. It is good to have a container option to run the project.

That said, three things would be nice:

- Update README to let the user know how to use the docker solution.
- The `Dockerfile` just sets an image from and run update. What is kinda not necessary. We could keep use just `docker-compose` and remove `Dockerfile`.
To do that, you can just remove the `build` directive from `Dockerfile` and replace the value of `image` to the dockerhub tag directly.
- Instead of `node:slim`, I think we could use `node:lts-alpine3.17`. Some reasons to do that: 
   - A more specific tag is usually easier to debug and won't change so easily (or even at all)
   - `slim` tag has more OS dependencies, for being [based on Debian](https://github.com/nodejs/docker-node/blob/f996e97a2e6d2aae2de3b869e083a253733f07a8/19/bullseye-slim/Dockerfile), so it is a bit larger image. And because it has more deps, it will have some more security vulnerabilities. On the other hand, `alpine` images are [based on Alpine linux](https://github.com/nodejs/docker-node/blob/f996e97a2e6d2aae2de3b869e083a253733f07a8/18/alpine3.17/Dockerfile), so it has less deps.
   - It is based on the last LTS. The image `node:slim` is based on the last released version, so now it is 19.6, tomorrow might be 19.8...20.3... There could be changes on node and/or vite and react that does not work together anymore.

2023-02-15 13:47 UTC, fabiofabbrucci commented
Thank you @renie for your kind feedback.
I've just pushed the fix you've just suggested.

I really appreciate your comments because they are extremely future-proof! 👏

2023-02-16 12:39 UTC, renie requested changes
Now there are just some minor fix to align docs with the real process.
The rest is pretty good, I've just tested with and without docker on my machine and everything works like a charm.
Thank you!

2023-02-16 12:39 UTC, renie commented on README.md
> +This project requires `Docker Desktop` intalled.
This project requires `NodeJS`, on version 18, or `Docker` installed. Depending on the way you prefer to run it.

2023-02-16 12:39 UTC, renie commented on README.md
> +cd qatest
`cd qatest` is already on the previous step after cloning

2023-02-16 12:39 UTC, renie commented on README.md
>  ## How to setup this project?
It says "install deps", but we are not installing deps on this step anymore.

2023-02-16 12:39 UTC, renie commented on README.md
> +Install dependencies in the new image.
Install dependencies and run `dev` script.

2023-02-16 12:39 UTC, renie commented on README.md
> +
Go to `docker` folder and start docker container.

2023-02-17 10:55 UTC, renie approved these changes

2023-02-17 11:01 UTC, merged